---
version: "3.7"

services:
  kratos-migrate:
    image: oryd/kratos:latest
    depends_on:
      - postgresd
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: -c /etc/kratos/kratos.yml migrate sql -e --yes
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/kratos
    networks:
      - intranet

  kratos:
    #  image: oryd/kratos:v0.8.0-alpha.3
    image: oryd/kratos:latest
    depends_on:
      - kratos-migrate
      - mailslurper
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/kratos
    networks:
      - intranet

  postgresd:
    image: postgres:14
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

networks:
  intranet:
